import "./globals.css";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/autoplay";
import "swiper/css/thumbs";
import dynamic from "next/dynamic";
// import { Toaster } from "react-hot-toast";
const Header = dynamic(() => import("@/components/Header"));
const Footer = dynamic(() => import("@/components/Footer"));

export const metadata = {
  title: "Audience",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
      </head>
      <body className={`antialiased`}>
        {/* <Toaster position="top-right" /> */}
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
